### ISSUE TITLE
histogram_sum usage in vicotria metrics

### ISSUE THREAD

**Issue by guy-frontegg** [grafana/xk6-output-prometheus-remote#125]
Hello All, 

You are doing a great job, thank you.

We are pushing the results as Prometheus remote write into VictoriaMetrics.
Yet when trying to use the dashboard (K6 Official Test result) it uses the experimental histogram_sum that VM does not support. What can we use differently to work with the dashboard?

Thank you

**Comment by codebien** [comment]
Hi @guy-frontegg,
VictoriaMetrics [doesn't support yet](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3733) the Native Histogram feature.

The k6 open-source dashboard requires the Native Histogram feature to be enabled and supported which means it will mostly work only with Prometheus and Mimir at the moment (they should still be the unique implementations that support the Native Histogram).

For using another Prometheus remote write implementation, [use the classic histogram](https://k6.io/docs/results-output/real-time/prometheus-remote-write/#counter-and-gauges) (the default option in this extension), and rewrite the panels' query to make them compatible.

**Comment by guy-frontegg** [comment]
Thank you @codebien,

This is very informative and for all the links.

I have to ask for help one last time, but only if it's possible. Because could not find a lot of material on histogram_sum functionality, and what the calculation suppose to do.

What can I replace it with?  sum(histogram)) ?

**Comment by codebien** [comment]
Hi @guy-frontegg,

>What can I replace it with? sum(histogram)) ?

If you meant in Victoria Metrics, I don't expect an equivalent function because the engine does not yet support the Native Histogram feature.

You can probably use the Trend conversion by [Counter&Gauges](https://k6.io/docs/results-output/real-time/prometheus-remote-write/#counter-and-gauges) but that means you've to use a custom dashboard rewriting most of the metrics for latencies.

I will close this issue as this is for the tracking features and bugs for the output and there isn't much we can do for this specific issue here. You may consider opening a topic in the [Forum](https://community.k6.io) or probably better on Victoria Metrics / Prometheus communities to get feedback on writing specific queries.
