### ISSUE TITLE
Bug: incorrect grouping of metrics during aggregation

### ISSUE THREAD

**Issue by yorugac** [grafana/xk6-output-prometheus-remote#13]
Described in community forum: https://community.k6.io/t/counters-not-starting-from-zero/2737
Both actual and expected behavior are included in the above description.

The cause: internal aggregation of metrics in the extension is happening by names of metrics and doesn't take labels into account. Ideally, this should be resolved by https://github.com/grafana/k6/issues/1831. However, that issue may take quite a lot of time to resolve fully, so it'd be good if a quicker solution can be added here first. E.g. once some design solutions proposed to https://github.com/grafana/k6/issues/1831, it might make sense to evaluate them here, in the extension first.

Currently considered blocked by https://github.com/grafana/k6/issues/1831 and should be re-visited upon progress there.

**Comment by mschenk42** [comment]
We've noticed trend metrics for requests with labels (name label in particular) are not correct.  When grouping by the name label (request) the trends are all the same for each name label.  Would this issue be why that is the case?

**Comment by codebien** [comment]
Hi @mschenk42, yes, it is the same issue. Hopefully, we will get fixed in the next releases, we are actively working on the main issue.

In the meanwhile, you could consider to workaround creating [custom metrics](https://k6.io/docs/using-k6/metrics/#custom-metrics) per endpoint, you probably need to tune the [System Tags](https://k6.io/docs/using-k6/tags-and-groups/#system-tags) so `k6` doesn't generate too much time series.
